import { GoogleGenAI, GenerateContentResponse } from "@google/genai";
import { Message } from "../types";

// Initialize GenAI
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

// Changed: We now check for a specific tag generated by the AI, rather than keywords.
// This prevents false positives (e.g. "How to treat vomiting" triggering a risk alert).
export const checkRisk = (text: string): boolean => {
  return text.includes("[RISK_DETECTED]");
};

export const sendMessageToAI = async (
  currentMessage: string,
  imageBase64: string | null,
  history: Message[]
): Promise<string> => {
  try {
    const systemInstruction = `
      你是一位经验丰富、富有同情心的AI宠物医生助手"宠医小助手"。

      【回答规范】
      1. **绝对禁止使用Markdown格式**。不要使用 **粗体**、## 标题、- 列表符等符号。
      2. 请使用自然的纯文本段落，通过换行和空格来组织内容，保持排版整洁清爽。
      3. 语气专业、温暖、令人安心。
      4. 回答要简洁，重点突出，便于手机阅读。

      【风险判断逻辑】
      只有当用户描述的情况**明显危及生命**或**需要立即急救**时（例如：大出血、呼吸困难、剧烈抽搐、误食剧毒、休克），请在回答的最开始加上 "[RISK_DETECTED]" 这个标记。
      
      如果是普通的呕吐、腹泻、皮肤病或日常咨询，**不要**加这个标记。

      【职责】
      1. 解答宠物健康、护理、营养问题。
      2. 解读化验单或病历图片（OCR），通俗解释数值。
      3. 始终提醒：你的回答仅供参考，不能替代线下诊疗。
    `;

    // Choose model based on content
    const modelId = imageBase64 ? 'gemini-2.5-flash-image' : 'gemini-3-flash-preview';
    
    // Prepare contents
    let contents: any = {};
    
    if (imageBase64) {
      // Multimodal request
      contents = {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: imageBase64.split(',')[1] 
            }
          },
          {
             text: currentMessage || "请帮我解读这张图片，如果是化验单请重点关注异常指标。请用纯文本回答，不要用Markdown。"
          }
        ]
      };
    } else {
      const conversationContext = history.slice(-5).map(h => `${h.role === 'user' ? '用户' : '医生'}: ${h.content}`).join('\n');
      const finalPrompt = `
        ${conversationContext}
        用户: ${currentMessage}
        医生:
      `;
       contents = { parts: [{ text: finalPrompt }] };
    }

    const response: GenerateContentResponse = await ai.models.generateContent({
      model: modelId,
      contents: contents,
      config: {
        systemInstruction: systemInstruction,
      }
    });

    return response.text || "抱歉，我没有理解您的意思，请再说一遍。";

  } catch (error) {
    console.error("Gemini API Error:", error);
    return "抱歉，AI 医生暂时繁忙，请稍后再试或直接咨询线下医生。";
  }
};